version: 0.2

env:
  parameter-store:
    S3_BUILD_ARTIFACTS_BUCKET: "build.artifacts.bucketname"
    S3_BUILD_ARTIFACTS_BUCKET_REGION: "build.artifacts.bucket.region"
    AWS_ACCESS_KEY_ID: "build.artifacts.s3.access.key"
    AWS_SECRET_ACCESS_KEY: "build.artifacts.s3.secret.key"

phases:
  build:
    commands:
      - echo "Enter build stage..."
      - npm --version
      - cd ucla-prrla; npm install; node_modules/.bin/ng build --no-progress
      - cd dist; tar -zcf ../test-prl.tar.gz .; cd -
      - rm -rf dist
      - node_modules/.bin/ng build --env=prod --no-sourcemap --no-progress
      - cd dist; tar -zcf ../prod-prl.tar.gz .; cd -
      - echo "Contents to copy to S3..."
      - ls -la *.tar.gz
  post_build:
    commands:
      - aws s3 cp test-prl.tar.gz s3://${S3_BUILD_ARTIFACTS_BUCKET}/prl/test-prl-latest.tar.gz
      - aws s3 cp prod-prl.tar.gz  s3://${S3_BUILD_ARTIFACTS_BUCKET}/prl/prod-prl-latest.tar.gz
