version: 0.2

env:
  variables:
    APP_ENV: "test-prl"
  parameter-store:
    S3_BUILD_ARTIFACTS_BUCKET: "build.artifacts.bucketname"
    S3_BUILD_ARTIFACTS_BUCKET_REGION: "build.artifacts.bucket.region"
    AWS_ACCESS_KEY_ID: "build.artifacts.s3.access.key"
    AWS_SECRET_ACCESS_KEY: "build.artifacts.s3.secret.key"

phases:
  build:
    commands:
      - echo "Enter build stage..."
      - npm --version
      - cd ucla-prrla; npm install --silent
      - if [[ ${APP_ENV} == "test-prl" ]]; then node_modules/.bin/ng build --no-progress; fi
      - if [[ ${APP_ENV} == "prod-prl" ]]; then node_modules/.bin/ng build --env=prod --no-sourcemap --no-progress; fi
      - cd dist; tar -zcf ../${APP_ENV}.tar.gz .; cd -
      - ls -la *.tar.gz
  post_build:
    commands:
      - aws s3 cp ${APP_ENV}.tar.gz  s3://${S3_BUILD_ARTIFACTS_BUCKET}/prl/${APP_ENV}-latest.tar.gz
      - aws s3 sync dist/ s3://${APP_ENV}.library.ucla.edu --delete
