version: 0.2

env:
  parameter-store:
    S3_BUILD_ARTIFACTS_BUCKET: "build.artifacts.bucketname"
    S3_BUILD_ARTIFACTS_BUCKET_REGION: "build.artifacts.bucket.region"
    S3_BUILD_ARTIFACTS_ACCESS_KEY: "build.artifacts.s3.access.key"
    S3_BUILD_ARTIFACTS_SECRET_KEY: "build.artifacts.s3.secret.key"

phases:
  build:
    commands:
      - echo "Enter build stage..."
      - npm --version
      - cd ucla-prrla; npm install; node_modules/.bin/ng build
      - mv dist dist.test
      - node_modules/.bin/ng build --env=prod --no-sourcemap
      - echo "Contents for prod..."
      - ls -la dist
      - echo "Contents for test..."
      - ls -la dist.test
#  post_build:
#    commands:
      #- |-
#         if [ "$BUILD_VERSION" = 'stable' ] ; then
#           AUTH="Authorization: token $AUTH_TOKEN"
#           TAG="$(curl -S -s -H "$AUTH" "$RELEASES" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c2-)" ;
#         else
#           TAG="latest" ;
#         fi
