version: 2
jobs:
  branches:
    only:
      - develop
  build:
    docker:
      - image: avuong/ubuntu-uclaprrla-deploy:latest
    steps:
      - checkout
      - run:
          name: Build static files via Angular
          command: |
            pwd
            ls -la
            npm --version
            uname -a
            cd ucla-prrla; npm install; node_modules/.bin/ng build
      - run:
          name: Drop robots.txt
          command: |
            echo "User-agent: *" > ucla-prrla/dist/robots.txt
            echo "Disallow: /" >> ucla-prrla/dist/robots.txt
      - deploy:
          name: Deploy to test site
          command: |
            which aws
            if [ $CIRCLE_BRANCH == "develop" ]
            then
            export AWS_ACCESS_KEY_ID=$develop_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$develop_AWS_SECRET_ACCESS_KEY
            aws s3 sync --delete ucla-prrla/dist/ s3://$develop_site/
            fi