name: Run CI Build

on:
  push:
    branches:
      - master
      - SERV-329
  pull_request:
    branches:
      - master

jobs:
  testbuildtestenv:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ucla-prrla
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: node_modules/.bin/ng build --no-progress
      - run: tar -zcf test-prl-latest.tar.gz dist
      - name: Copy Artifact to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.BUILDARTIFACTS_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: 'ucla-prrla/test-prl-latest.tar.gz'
      - name: deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.TESTPRL_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: 'ucla-prrla/dist'
  testbuildprodenv:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ucla-prrla
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: node_modules/.bin/ng build --env=prod --no-sourcemap --no-progress
